name: my_music
description: A 3D Music Player App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Audio
  audio_service: ^0.18.9
  just_audio: ^0.9.35
  rxdart: ^0.27.7
  
  # File & Storage
  file_picker: ^5.5.0
  shared_preferences: ^2.2.2
  
  # Permissions
  permission_handler: ^10.4.3
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
