name: my_music
description: A 3D Music Player App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Audio & File
  audioplayers: ^5.0.0
  file_picker: ^5.5.0
  permission_handler: ^10.4.3
  
  # Background Audio
  audio_service: ^0.18.10
  just_audio: ^0.9.36
  audio_session: ^0.1.17
  
  # UI & Utils
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0A0A0F"
  adaptive_icon_foreground: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0A0A0F"
  image: assets/icon/icon.png
  android: true
  ios: false
  android_gravity: center
  color_dark: "#0A0A0F"
  image_dark: assets/icon/icon.png
  
  android_12:
    color: "#0A0A0F"
    image: assets/icon/icon.png
    color_dark: "#0A0A0F"
    image_dark: assets/icon/icon.png
