name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true

    - name: Initialize Android Module
      run: |
        flutter create . --platforms=android --project-name=my_music --org=com.vmusic.app
        rm -rf android
        flutter create . --platforms=android --project-name=my_music --org=com.vmusic.app

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: music-apk-v1
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 1
