name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true

    - name: Initialize Android Module
      run: |
        flutter create . --platforms=android --project-name=my_music --org=com.vmusic.app
        rm -rf android
        flutter create . --platforms=android --project-name=my_music --org=com.vmusic.app

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --debug
  
    - name: Send APK to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -F chat_id="$TELEGRAM_CHAT_ID" \
             -F document=@"build/app/outputs/flutter-apk/app-debug.apk" \
             -F caption="Lo bhai, aapka My-Music APK ready hai! 🎵" \
             "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument"
